### PR TITLE
Resolve issue #6

### PR DESCRIPTION
**Pull request by thorstenwagner**
To fix issue https://github.com/rwl/ParallelColt/issues/6:

I've changed the dependency to JTransform 3.1 and renamed the edu.emory.mathcs.utils package into 
edu.emory.mathcs.utils.pc.ConcurrencyUtils

The units tests are successful.

### CODE REVIEW

**Comment by thorstenwagner** [comment]
The failed unit test seems to be only a minor problem due to the change of jtransform:
testAggregateComplexComplexComplexFunctionComplexComplexFunction(cern.colt.matrix.tfcomplex.impl.LargeDenseFComplexMatrix3DTest): expected: **858.34784** but was: **858.3467**

**Comment by ctrueden** [comment]
More correct would be to use the `cern` package prefix for the renamed class(es), since it is a fork for ParallelColt's usage only. But still: :+1: for avoiding class clashes!

**Comment by beyondpie** [comment]
Hi, how can I include this package in pom ? I saw a version on 2013....

**Comment by ctrueden** [comment]
@songpeng 
```xml
<dependency>
  <groupId>net.sourceforge.parallelcolt</groupId>
  <artifactId>parallelcolt</artifactId>
  <version>0.10.1</version>
</dependency>
```

**Comment by beyondpie** [comment]
Thanks, but I just use this one, and it seemed  to be older than the solved version. And it still has this problem.

**Comment by ctrueden** [comment]
@songpeng Oh, sorry, I didn't check the version carefully enough. It seems `0.11.4` was the last release according to the master branch here. But `0.10.1` is the latest version I see in Maven Central.

@rwl Where are you deploying releases these days?

**Comment by tischi** [comment]
Hi All,
Is there any update on that? I am also running into the circular dependency issue of version 0.10.1

**Comment by tischi** [comment]
Also version 0.11.2 seems broken
```
 Found in:
    net.sourceforge.jplasma:jplasma:jar:1.2.0:compile
    net.sourceforge.parallelcolt:parallelcolt:jar:0.11.2-SNAPSHOT:compile
  Duplicate classes:
    edu/emory/mathcs/utils/ConcurrencyUtils$CustomThreadFactory.class
    edu/emory/mathcs/utils/ConcurrencyUtils$CustomExceptionHandler.class
    edu/emory/mathcs/utils/ConcurrencyUtils.class
```

**Comment by ctrueden** [comment]
@tischi I did some digging, and will comment further on issue #6.

**Comment by AdamM68** [comment]
I found the same problem in my project  ( Android Studio 4.1 )

_Duplicate class edu.emory.mathcs.utils.ConcurrencyUtils found in the following modules: jetified-jplasma-1.2.0 (net.sourceforge.jplasma:jplasma:1.2.0), jetified-jtransforms-2.4.0 (net.sourceforge.jtransforms:jtransforms:2.4.0) and jetified-parallelcolt-0.10.1 (net.sourceforge.parallelcolt:parallelcolt:0.10.1)
Duplicate class edu.emory.mathcs.utils.ConcurrencyUtils$CustomExceptionHandler found in the following modules: jetified-jplasma-1.2.0 (net.sourceforge.jplasma:jplasma:1.2.0), jetified-jtransforms-2.4.0 (net.sourceforge.jtransforms:jtransforms:2.4.0) and jetified-parallelcolt-0.10.1 (net.sourceforge.parallelcolt:parallelcolt:0.10.1)
Duplicate class edu.emory.mathcs.utils.ConcurrencyUtils$CustomThreadFactory found in the following modules: jetified-jplasma-1.2.0 (net.sourceforge.jplasma:jplasma:1.2.0), jetified-jtransforms-2.4.0 (net.sourceforge.jtransforms:jtransforms:2.4.0) and jetified-parallelcolt-0.10.1 (net.sourceforge.parallelcolt:parallelcolt:0.10.1)
Duplicate class edu.emory.mathcs.utils.IOUtils found in modules jetified-jtransforms-2.4.0 (net.sourceforge.jtransforms:jtransforms:2.4.0) and jetified-parallelcolt-0.10.1 (net.sourceforge.parallelcolt:parallelcolt:0.10.1)_

Is there a solution for this problem ?

**Pull request merged**
